ruisoArtPage/Controllers/BannerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ruisoArtPage.Data;
using ruisoArtPage.Data;
using ruisoArtPage.Data.Static;
using ruisoArtPage.Models;
using X.PagedList;

namespace ruisoArtPage.Controllers{
    public class BannerController : Controller{
        private readonly ApplicationDbContext _context;
        public BannerController(ApplicationDbContext context){
            _context = context;
        }
        //-------------------------------------------------------------- INDEX
        /*public async Task <IActionResult> Index(){
            var allBanners = await _context.Banner.ToListAsync();
            return View(allBanners);
        }*/
        public IActionResult Index(string sortOn, string orderBy, string pSortOn, int? page) {
            int recordsPerPage = 2;
            if (!page.HasValue) {
                page = 1;
                orderBy = string.IsNullOrWhiteSpace(orderBy) || orderBy.Equals("asc") ? "desc" : "asc";
            } if (!string.IsNullOrWhiteSpace(sortOn) && !sortOn.Equals(pSortOn, StringComparison.CurrentCultureIgnoreCase)){
                orderBy = "asc";
            }

            ViewBag.OrderBy = orderBy;
            ViewBag.SortOn = sortOn;
            var data = _context.Banner.AsQueryable();
            switch (sortOn) {
                case "Name":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.Name) : data.OrderByDescending(i => i.Name);
                    break;
                case "Description":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.Description) : data.OrderByDescending(i => i.Description);
                    break;
                case "size":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.size) : data.OrderByDescending(i => i.size);
                    break;
                case "link":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.link) : data.OrderByDescending(i => i.link);
                    break;
                case "ProviderId":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.ProviderId) : data.OrderByDescending(i => i.ProviderId);
                    break;
                default:
                    data = data.OrderBy(i => i.Id);
                    break;
            }

            ViewBag.banners = data.ToPagedList(page.Value, recordsPerPage);
            return View(data);
        }
        //-------------------------------------------------------------- DETAILS
        public IActionResult Details(int id)        {
            var data = _context.Banner.FirstOrDefault(a => a.Id == id);
            if (data == null){
                return View("NotFound");
            }
            return View(data);
        }
        //-------------------------------------------------------------- EDIT
        [Authorize(Roles = UserRoles.Admin)]
        public IActionResult Edit(int id){
            var data = _context.Banner.FirstOrDefault(a => a.Id == id);
            if (data == null){
                return View("NotFound");
            }
            return View(data);
        }
        [Authorize(Roles = UserRoles.Admin)]
        [HttpPost]
        public IActionResult Edit(int id, 
        [Bind("Id, Name, Description, size, image, link, ProviderId")] Banner data){
            if(!ModelState.IsValid){
                return View(data);
            }
            if(id == data.Id){
                _context.Banner.Update(data);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(data);
        }
        //-------------------------------------------------------------- DELETE
        [Authorize(Roles = UserRoles.Admin)]
        public IActionResult Delete(int id){
            var data = _context.Banner.FirstOrDefault(a => a.Id == id);
            return View(data);
        }
        [Authorize(Roles = UserRoles.Admin)]
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int id){
            var data = _context.Banner.FirstOrDefault(a=> a.Id == id);
            if(data == null) return View("NotFound");
            _context.Banner.Remove(data);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        //-------------------------------------------------------------- CREATE
        [Authorize(Roles = UserRoles.Admin)]
        public IActionResult Create(){
            return View();
        }
        [Authorize(Roles = UserRoles.Admin)]
        [HttpPost]
        public IActionResult Create(
            [Bind("Name, Description, size, image, link, ProviderId")] Banner data){
            if(!ModelState.IsValid){
                return View(data);
            }

            _context.Banner.Add(data);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }
    }
}

ruisoArtPage/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ruisoArtPage.Data;
using ruisoArtPage.Data.Static;
using ruisoArtPage.Models;
using X.PagedList;

namespace ruisoArtPage.Controllers{
    public class ProductController : Controller{
        private readonly ApplicationDbContext _context;
        public ProductController(ApplicationDbContext context){
            _context = context;
        }
        //-------------------------------------------------------------- INDEX
        /*public async Task <IActionResult> Index(){
            var all = await _context.Product.ToListAsync();
            return View(all);
        }*/
        public IActionResult Index(string sortOn, string orderBy, string pSortOn, int? page){
            int recordsPerPage = 2;
            if (!page.HasValue) {
                page = 1;
                orderBy = string.IsNullOrWhiteSpace(orderBy) || orderBy.Equals("asc") ? "desc" : "asc";
            } if (!string.IsNullOrWhiteSpace(sortOn) && !sortOn.Equals(pSortOn, StringComparison.CurrentCultureIgnoreCase)){
                orderBy = "asc";
            }

            ViewBag.OrderBy = orderBy;
            ViewBag.SortOn = sortOn;
            var data = _context.Product.AsQueryable();
            switch (sortOn) {
                // name, description, image, price, tax, quantity, shoppingWay
                case "name":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.name) : data.OrderByDescending(i => i.name);
                    break;
                case "description":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.description) : data.OrderByDescending(i => i.description);
                    break;
                case "price":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.price) : data.OrderByDescending(i => i.price);
                    break;
                case "tax":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.tax) : data.OrderByDescending(i => i.tax);
                    break;
                case "quantity":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.quantity) : data.OrderByDescending(i => i.quantity);
                    break;
                case "shoppingWay":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.shoppingWay) : data.OrderByDescending(i => i.shoppingWay);
                    break;
                // creationDate, externalLink, nftLink, color, sizeCup, modelClothes, sizeClothes, sizeNotepad, season, 
                // status, sizePrint, sizePaper, formatImage, sizeBookMarker, rolDice, sizeDice, TypeId
                case "creationDate":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.creationDate) : data.OrderByDescending(i => i.creationDate);
                    break;
                case "externalLink":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.externalLink) : data.OrderByDescending(i => i.externalLink);
                    break;
                case "nftLink":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.nftLink) : data.OrderByDescending(i => i.nftLink);
                    break;
                case "color":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.color) : data.OrderByDescending(i => i.color);
                    break;
                case "sizeCup":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.sizeCup) : data.OrderByDescending(i => i.sizeCup);
                    break;
                case "modelClothes":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.modelClothes) : data.OrderByDescending(i => i.modelClothes);
                    break;
                case "sizeClothes":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.sizeClothes) : data.OrderByDescending(i => i.sizeClothes);
                    break;
                case "sizeNotepad":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.sizeNotepad) : data.OrderByDescending(i => i.sizeNotepad);
                    break;
                case "season":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.season) : data.OrderByDescending(i => i.season);
                    break;
                case "status":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.status) : data.OrderByDescending(i => i.status);
                    break;
                case "sizePrint":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.sizePrint) : data.OrderByDescending(i => i.sizePrint);
                    break;
                case "sizePaper":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.sizePaper) : data.OrderByDescending(i => i.sizePaper);
                    break;
                case "formatImage":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.formatImage) : data.OrderByDescending(i => i.formatImage);
                    break;
                case "sizeBookMarker":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.sizeBookMarker) : data.OrderByDescending(i => i.sizeBookMarker);
                    break;
                case "rolDice":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.rolDice) : data.OrderByDescending(i => i.rolDice);
                    break;
                case "sizeDice":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.sizeDice) : data.OrderByDescending(i => i.sizeDice);
                    break;
                /*case "TypeId":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.TypeId) : data.OrderByDescending(i => i.TypeId);
                    break;*/
                case "ProviderId":
                    data = orderBy.Equals("asc") ? data.OrderBy(i => i.ProviderId) : data.OrderByDescending(i => i.ProviderId);
                    break;
                default:
                    data = data.OrderBy(i => i.Id);
                    break;
            }

            ViewBag.products = data.ToPagedList(page.Value, recordsPerPage);
            return View(data);
        }
        //-------------------------------------------------------------- DETAILS 
        public IActionResult Details(int id)        {
            var data = _context.Product.FirstOrDefault(a => a.Id == id);
            if (data == null){
                return View("NotFound");
            }
            return View(data);
        }
        //-------------------------------------------------------------- EDIT
        [Authorize(Roles = UserRoles.Admin)]
        public IActionResult Edit(int id){
            var data = _context.Product.FirstOrDefault(a => a.Id == id);
            if (data == null){
                return View("NotFound");
            }
            return View(data);
        }
        [Authorize(Roles = UserRoles.Admin)]
        [HttpPost]
        public IActionResult Edit(int id, 
        [Bind("Id, name, description, image, price, tax, quantity, shoppingWay, creationDate, externalLink, nftLink, color, sizeCup, modelClothes, sizeClothes, sizeNotepad, season, status, sizePrint, sizePaper, formatImage, sizeBookMarker, rolDice, sizeDice, ProviderId")] Product data){
            if(!ModelState.IsValid){
                return View(data);
            }
            if(id == data.Id){
                _context.Product.Update(data);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(data);
        }
        //-------------------------------------------------------------- DELETE
        [Authorize(Roles = UserRoles.Admin)]
        public IActionResult Delete(int id){
            var data = _context.Product.FirstOrDefault(a => a.Id == id);
            return View(data);
        }
        [Authorize(Roles = UserRoles.Admin)]
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int id){
            var data = _context.Product.FirstOrDefault(a=> a.Id == id);
            if(data == null) return View("NotFound");
            _context.Product.Remove(data);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        //-------------------------------------------------------------- CREATE
        [Authorize(Roles = UserRoles.Admin)]
        public IActionResult Create(){
            return View();
        }
        [Authorize(Roles = UserRoles.Admin)]
        [HttpPost]
        public IActionResult Create([Bind("name, description, image, price, tax, quantity, shoppingWay, creationDate, externalLink, nftLink, color, sizeCup, modelClothes, sizeClothes, sizeNotepad, season, status, sizePrint, sizePaper, formatImage, sizeBookMarker, rolDice, sizeDice, ProviderId")] Product data){
            if(!ModelState.IsValid){
                return View(data);
            }
            _context.Product.Add(data);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    
    
        //--------------------------------------------------------------
        public Product GetProductById(int id){
            
            return _context.Product
                .Include(dc => dc.DocProducts)
                .ThenInclude(d => d.Document)
                .Include(cp => cp.CategoryProducts)
                .ThenInclude(c => c.Category)
                .Include(po => po.Provider)
                .FirstOrDefault(a => a.Id == id);
        }
    }
}

ruisoArtPage/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-12 offset-0">
        <h3 class="text-info">This item was not found!</h3>
        <hr />
        <img style="width:100%" src="https://images.unsplash.com/photo-1633078654544-61b3455b9161?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1045&q=80"/>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Home" asp-action="Index">Home</a>
    </div>
</div>

ruisoArtPage/Views/Shared/_CreateItem.cshtml
@model string;

<div class="text-white mb-4" style="position: fixed; right: 25px; bottom: 38px;">
    <a class="btn btn-success" asp-controller="@Model" asp-action="Create">
        <i class="bi bi-plus-circle"></i>
        Add New
    </a>
</div>

ruisoArtPage/Views/Shared/_Layout.cshtml
@using ruisoArtPage.Data.Static;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ruisoArtPage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ruisoArtPage.styles.css" asp-append-version="true" />
    <!-- https://icons.getbootstrap.com/ >> CDN -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">RuisoArtPage</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Commission" asp-action="Create">Commission</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        @if(User.Identity.IsAuthenticated && User.IsInRole(UserRoles.Admin)){

                            <li class="nav-item dropdown">
                                <a class="nav-link-dorpdown-toogle" href="#" id="navbarDropdown" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear-fill"></i>Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    @*<a class="dropdown-item" asp-controller="Item" asp-action="Index"><i class="bi bi-box"></i> Item</a>*@
                                    <a class="dropdown-item" asp-controller="Product" asp-action="Index"><i class="bi bi-easel"></i> Product</a>
                                    <a class="dropdown-item" asp-controller="Provider" asp-action="Index"><i class="bi bi-person-bounding-box"></i> Provider</a>
                                    <a class="dropdown-item" asp-controller="Commission" asp-action="Index"><i class="bi bi-brush"></i> Commission</a>
                                    <a class="dropdown-item" asp-controller="Document" asp-action="Index"><i class="bi bi-file-earmark-bar-graph"></i> Document</a>
                                    <a class="dropdown-item" asp-controller="Banner" asp-action="Index"><i class="bi bi-star"></i> Banner</a>
                                </div>
                            </li>
                        }  
                    </ul>
                    @*Nuevo por shopping*@
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="myHeader">
        <section class="myTextHeader">
            <h1>Ruiso Art Page</h1>
            <h2>-Sale of art and articles made by RuisoArt-</h2>
        </section>
        <div class="wave" style="height: 150px; overflow: hidden;" >
            <svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
                <path d="M-1.12,108.06 C212.75,149.50 320.53,47.86 500.00,103.13 L500.00,150.00 L0.00,150.00 Z" style="stroke: none; fill: #FFFFFF;"></path>
            </svg>
        </div>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="container">
        <div class="contact">
            <section class="extra">
                <h1 class="Text_contact">Ruiso Art Page</h1>
            </section>
            <section class="myFtexts">
                <h1 class="Text_contact">Contact to Me!</h1>
            </section>
            <section class="extra_2"></section>
            <section class="extra">
                <a href="https://linktr.ee/onruisoart">
                    <button type="button" class="btn btn-light" style="width: 200px">
                        <img src="http://localhost/images/linktree-logo-0 (2).png" style="width: 150px"/>
                    </button>
                </a>
            </section>
            <section class="extra_2"></section>
            <div class="row align-items-center">
                <div class="col"></div>
                <div class="col">
                    <a href="https://user.zepeto.me/ruisoart?referrer=ruisoart">
                        <img src="http://localhost/images/1_528Zt3gJU4qMVXqh-nzIXQ.png" style="width: 70px"/>
                    </a>
                </div>
                <div class="col">
                    <a href="https://www.facebook.com/ruisoart">
                        <img src="http://localhost/images/facebook.png" style="width: 70px"/>
                    </a>
                </div>
                <div class="col">
                    <a href="https://github.com/RuisoArt">
                        <img src="http://localhost/images/github.png" style="width: 70px"/>
                    </a>
                </div>
                <div class="col">
                    <a href="ruiso.trabajoscomisiones@gmail.com">
                        <img src="http://localhost/images/gmail.png" style="width: 70px"/>
                    </a>
                </div>
                <div class="col">
                    <a href="https://twitter.com/RuisoArt">
                        <img src="http://localhost/images/gorjeo.png" style="width: 70px"/>
                    </a>
                </div>
                <div class="col">
                    <a href="https://www.instagram.com/onruisoart/">
                        <img src="http://localhost/images/instagram.png" style="width: 70px"/>
                    </a>
                </div>
                <div class="col">
                    <a href="https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0001701491">
                        <img src="http://localhost/images/R (1).png" style="width: 70px"/>
                    </a>
                </div>
                <div class="col">
                    <a href="https://shre.ink/H0gP">
                        <img src="http://localhost/images/R.png" style="width: 70px"/>
                    </a>
                </div>
                <div class="col">
                    <a href="https://ruisoart.tumblr.com/">
                        <img src="http://localhost/images/tumblr.png" style="width: 70px"/>
                    </a>
                </div>
                <div class="col">
                    <a href="https://www.twitch.tv/onruiso97">
                        <img src="http://localhost/images/twitch.png" style="width: 70px"/>
                    </a>
                </div>
                <div class="col">
                    <a href="https://www.youtube.com/channel/UCPSeMEXj7ZhJdNjXedrgTug">
                        <img src="http://localhost/images/youtube.png" style="width: 70px"/>
                    </a>
                </div>
                <div class="col">
                    <a href="https://www.deviantart.com/onruisoart">
                        <img src="http://localhost/images/devi.png" style="width: 70px"/>
                    </a>
                </div>
                <div class="col"></div>
            </div>
            
        </div>
    </div>

    <div class="preFooter">
        <p>-Back-</p>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">

            <div class="conteiner_footer">
                <div class="content_foo">
                    <h4>columna 1</h4>
                    <p>dato aja: #$%&/!"#!"#123</p>
                    <p>dato aja: #$%&/!"#!"#123</p>
                    <p>dato aja: #$%&/!"#!"#123</p>
                </div>
                <div class="content_foo">
                    <h4>columna 2</h4>
                    <p>dato aja: #$%&/!"#!"#123</p>
                    <p>dato aja: #$%&/!"#!"#123</p>
                    <p>dato aja: #$%&/!"#!"#123</p>
                </div>
                <div class="content_foo">
                    <h4>columna 3</h4>
                    <p>dato aja: #$%&/!"#!"#123</p>
                    <p>dato aja: #$%&/!"#!"#123</p>
                    <p>dato aja: #$%&/!"#!"#123</p>
                </div>
                <div class="content_foo">
                    <h4>columna 4</h4>
                    <p>dato aja: #$%&/!"#!"#123</p>
                    <p>dato aja: #$%&/!"#!"#123</p>
                    <p>dato aja: #$%&/!"#!"#123</p>
                </div>
            </div>

            <div class="conteiner_footer">
                <div class="content_foo">
                    <h4>columna 6</h4>
                    <p>dato aja: #$%&/!"#!"#123</p>
                    <p>dato aja: #$%&/!"#!"#123</p>
                    <p>dato aja: #$%&/!"#!"#123</p>
                </div>
                <div class="content_foo">
                    <h4>columna 7</h4>
                    <p>dato aja: #$%&/!"#!"#123</p>
                    <p>dato aja: #$%&/!"#!"#123</p>
                    <p>dato aja: #$%&/!"#!"#123</p>
                </div>
                <div class="content_foo">
                    <h4>columna 8</h4>
                    <p>dato aja: #$%&/!"#!"#123</p>
                    <p>dato aja: #$%&/!"#!"#123</p>
                    <p>dato aja: #$%&/!"#!"#123</p>
                </div>
                <div class="content_foo">
                    <h4>columna 9</h4>
                    <p>dato aja: #$%&/!"#!"#123</p>
                    <p>dato aja: #$%&/!"#!"#123</p>
                    <p>dato aja: #$%&/!"#!"#123</p>
                </div>
            </div>

            <div class="separator"></div>
             
            <h5 class="tittle_final">
                &copy; 2023 - ruisoArtPage - Ing.Luis Felipe Narvaez Gomez
                <a asp-area="" asp-controller="Home" asp-action="Privacy" value="Privacy"/>
            </h5>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>